### ISSUE TITLE
Is the virtual retina model integrated in corem?

### ISSUE THREAD

**Issue by Thanh-Binh** [pablomc88/COREM#7]
I am interested in knowing what corem is better than the VirtualRetina model from Inria?

**Comment by pablomc88** [comment]
Hi,
Virtual Retina is, as you said, a retina model. COREM is a configurable simulator that provides the user with a set of basic building blocks to construct a wide repertoire of retina models. Indeed, we have also implemented a version of the Virtual retina model.

**Comment by Thanh-Binh** [comment]
Can i access the output data of retina like generated spikes and ganlion layr outputs at every frame image? Thx

**Comment by pablomc88** [comment]
Thanh-Binh, 
would you give me your email address so that we can continue this conversation on these off-topic technical issues?

**Comment by Thanh-Binh** [comment]
My email: thanh-binh.to@online.de
