### ISSUE TITLE
No 'parse_help.py' file

### ISSUE THREAD

**Issue by L24358** [pablomc88/COREM#8]
Hello,
I've installed nest 2.16.0 on Ubuntu 16.04. When I try to build the interface to nest, this error occurs:
`$make install`
`python: can't open file 'parse_help.py': [Errno 2] No such file or directory`

Please help.

**Comment by pablomc88** [comment]
Hi,
The reason is that the help generation in the CMakeLists.txt of NEST 2.16 has been modified with regard to previous versions. In any case, the interface module of COREM is correctly compiled and installed, so you can work with it. Thank you for your comment.

**Comment by pablomc88** [comment]
I have changed the CMakeLists.txt of the interface module to make it compatible with NEST 2.16.
